create table products (
	id BIGSERIAL PRIMARY KEY,
	product_name VARCHAR(50),
	price DECIMAL(10,2)
);

insert into products (id, product_name, price) values (1, 'Pet Food Storage Container', 3304.58);
insert into products (id, product_name, price) values (2, 'Tomato Sauce', 6045.76);
insert into products (id, product_name, price) values (3, 'Stuffed Bell Peppers', 1261.97);
insert into products (id, product_name, price) values (4, 'Foot Massager Machine', 3385.64);
insert into products (id, product_name, price) values (5, 'Window Blinds', 490.55);
insert into products (id, product_name, price) values (6, 'Multi-Function Meat Tenderizer', 7207.96);
insert into products (id, product_name, price) values (7, 'Maple Pecan Oatmeal Cookies', 145.25);
insert into products (id, product_name, price) values (8, 'LED Strip Light Kit', 6598.14);
insert into products (id, product_name, price) values (9, 'Crispy Kale Chips', 2913.16);
insert into products (id, product_name, price) values (10, 'LED Desk Lamp with USB Charging', 8566.16);
insert into products (id, product_name, price) values (11, 'Puff Pastry', 8117.71);
insert into products (id, product_name, price) values (12, 'Kale Salad with Lemon Dressing', 3466.07);
insert into products (id, product_name, price) values (13, '3D Night Light', 8742.63);
insert into products (id, product_name, price) values (14, 'Chia Seed Pudding Mix', 5837.35);
insert into products (id, product_name, price) values (15, 'Microfiber Cleaning Cloth Set', 8291.93);
insert into products (id, product_name, price) values (16, 'Blueberry Muffin Mix', 1222.78);
insert into products (id, product_name, price) values (17, 'Emergency Preparedness Kit', 4720.02);
insert into products (id, product_name, price) values (18, 'Rice Pudding', 9722.81);
insert into products (id, product_name, price) values (19, 'Potting Soil', 1478.93);
insert into products (id, product_name, price) values (20, 'Backpack', 754.37);
insert into products (id, product_name, price) values (21, 'Magnetic Phone Case', 7877.60);
insert into products (id, product_name, price) values (22, 'Ceramic Cookware Set', 1417.31);
insert into products (id, product_name, price) values (23, 'Chia Seed Pudding', 5174.57);
insert into products (id, product_name, price) values (24, 'Pretzel Bites', 6096.56);
insert into products (id, product_name, price) values (25, 'Salt and Pepper Grinder Set', 217.77);
insert into products (id, product_name, price) values (26, 'Spinach and Cheese Quiche', 9158.37);
insert into products (id, product_name, price) values (27, 'Fresh Lemons', 9624.57);
insert into products (id, product_name, price) values (28, 'Deep Tissue Massage Gun', 7431.13);
insert into products (id, product_name, price) values (29, 'Ice Pack', 8635.23);
insert into products (id, product_name, price) values (30, 'Adjustable Kitchen Broom Stand', 5907.91);
insert into products (id, product_name, price) values (31, 'Garden Tool Set', 2098.66);
insert into products (id, product_name, price) values (32, 'Mango Chilli Sauce', 4606.23);
insert into products (id, product_name, price) values (33, 'Over-The-Door Shoe Organizer', 9835.32);
insert into products (id, product_name, price) values (34, 'Chili Beans (canned)', 5803.71);
insert into products (id, product_name, price) values (35, 'Frozen Burritos', 8691.16);
insert into products (id, product_name, price) values (36, 'A-Line Skirt', 2161.00);
insert into products (id, product_name, price) values (37, 'Chunky Knit Sweater', 1350.50);
insert into products (id, product_name, price) values (38, 'Mediterranean Chickpea Bowl', 612.20);
insert into products (id, product_name, price) values (39, 'Biodegradable Phone Case', 3101.56);
insert into products (id, product_name, price) values (40, 'Vegetable Stir-Fry Kit', 586.64);
insert into products (id, product_name, price) values (41, 'Handheld Shower Head', 2202.62);
insert into products (id, product_name, price) values (42, 'Sporty Slide Sandals', 5936.99);
insert into products (id, product_name, price) values (43, 'Photo Album', 3089.13);
insert into products (id, product_name, price) values (44, 'Electric Griddle with Lid', 1199.37);
insert into products (id, product_name, price) values (45, 'Insulated Lunch Bag', 4623.29);
insert into products (id, product_name, price) values (46, 'Dark Chocolate Raisins', 8205.51);
insert into products (id, product_name, price) values (47, 'Granulated Sugar', 618.36);
insert into products (id, product_name, price) values (48, 'Pomegranate Juice', 8703.04);
insert into products (id, product_name, price) values (49, 'Wireless Printer', 4885.46);
insert into products (id, product_name, price) values (50, 'Puff Pastry', 4945.70);
insert into products (id, product_name, price) values (51, 'Beef Stroganoff Mix', 5349.09);
insert into products (id, product_name, price) values (52, 'Dark Chocolate Raisins', 1334.05);
insert into products (id, product_name, price) values (53, 'Sliced Provolone Cheese', 9433.23);
insert into products (id, product_name, price) values (54, 'Sustainable Wooden Toys', 5193.56);
insert into products (id, product_name, price) values (55, 'Pumpkin Spice Cookies', 6481.42);
insert into products (id, product_name, price) values (56, 'Customizable Wall Calendar', 3056.12);
insert into products (id, product_name, price) values (57, 'Cheesy Cauliflower Bake', 194.64);
insert into products (id, product_name, price) values (58, 'Salsa', 6359.61);
insert into products (id, product_name, price) values (59, 'Frozen Acai Bowl', 8085.69);
insert into products (id, product_name, price) values (60, 'Noise-Canceling Earbuds', 9439.84);
insert into products (id, product_name, price) values (61, 'Basketball', 4404.54);
insert into products (id, product_name, price) values (62, 'Cilantro Lime Rice', 1994.57);
insert into products (id, product_name, price) values (63, 'Chocolate Almond Milk', 4033.25);
insert into products (id, product_name, price) values (64, 'Chocolate Fudge Brownie Mix', 8353.15);
insert into products (id, product_name, price) values (65, 'Hot Salsa', 6365.82);
insert into products (id, product_name, price) values (66, 'Fruit & Nut Trail Mix', 6746.02);
insert into products (id, product_name, price) values (67, 'Biodegradable Dog Waste Bags', 1106.73);
insert into products (id, product_name, price) values (68, 'Electric Air Pump', 3003.16);
insert into products (id, product_name, price) values (69, 'Coconut Bowls Set', 4891.10);
insert into products (id, product_name, price) values (70, 'Magnetic Screen Door', 3040.34);
insert into products (id, product_name, price) values (71, 'Leather Crossbody Bag', 9011.64);
insert into products (id, product_name, price) values (72, 'Wireless Wi-Fi Extender', 5285.18);
insert into products (id, product_name, price) values (73, 'Body Wash', 1841.07);
insert into products (id, product_name, price) values (74, 'Samsung Galaxy Smartwatch', 5591.77);
insert into products (id, product_name, price) values (75, 'Portable Hammock', 3189.32);
insert into products (id, product_name, price) values (76, 'Chocolate Almond Milk', 4489.03);
insert into products (id, product_name, price) values (77, 'Digital Stopwatch Timer', 9087.46);
insert into products (id, product_name, price) values (78, 'Pet Hair Vacuum Cleaner Attachment', 4704.23);
insert into products (id, product_name, price) values (79, 'Outdoor Adventure Backpack', 8601.36);
insert into products (id, product_name, price) values (80, 'Travel Makeup Organizer', 1888.39);
insert into products (id, product_name, price) values (81, 'Sous Vide Cooker', 827.21);
insert into products (id, product_name, price) values (82, 'Essential Oils Diffuser Necklace', 9282.75);
insert into products (id, product_name, price) values (83, 'Oven-Baked Potato Chips', 4310.75);
insert into products (id, product_name, price) values (84, 'Balsamic Salad Dressing', 131.18);
insert into products (id, product_name, price) values (85, 'Caramelized Onion Dip', 9909.28);
insert into products (id, product_name, price) values (86, 'Lentil Soup (canned)', 1864.26);
insert into products (id, product_name, price) values (87, 'Adjustable Pet Grooming Table', 3652.75);
insert into products (id, product_name, price) values (88, 'French Bread', 9614.71);
insert into products (id, product_name, price) values (89, 'DIY Organic Gardening Kit', 3812.06);
insert into products (id, product_name, price) values (90, 'Portable Phone Charger', 6616.61);
insert into products (id, product_name, price) values (91, 'Rechargeable Electric Screwdriver', 3131.51);
insert into products (id, product_name, price) values (92, 'Slingback Sandals', 5007.25);
insert into products (id, product_name, price) values (93, 'Fitbit Activity Tracker', 853.11);
insert into products (id, product_name, price) values (94, 'Magnetic Chess Set', 1025.68);
insert into products (id, product_name, price) values (95, 'Wireless Earbud Silicone Covers', 7826.47);
insert into products (id, product_name, price) values (96, 'Personal Blender with Travel Cup', 884.61);
insert into products (id, product_name, price) values (97, 'Multi-Function Smartphone Holder', 7334.98);
insert into products (id, product_name, price) values (98, 'Fruit & Nut Trail Mix', 6623.19);
insert into products (id, product_name, price) values (99, 'Kale and Quinoa Salad', 2777.87);
insert into products (id, product_name, price) values (100, 'Peanut Butter Banana Smoothie Mix', 9641.24);
insert into products (id, product_name, price) values (101, 'Savory Pumpkin Soup', 4878.99);
insert into products (id, product_name, price) values (102, 'Pumpkin Spice Pancake Mix', 9634.55);
insert into products (id, product_name, price) values (103, 'Jalapeño Cornbread', 2836.77);
insert into products (id, product_name, price) values (104, 'Utility Cargo Pants', 5018.64);
insert into products (id, product_name, price) values (105, 'Snack Container Set', 3829.67);
insert into products (id, product_name, price) values (106, 'Thai Basil Fried Rice', 3585.17);
insert into products (id, product_name, price) values (107, 'Chocolate Syrup', 1342.57);
insert into products (id, product_name, price) values (108, 'Sesame Garlic Noodles', 4765.54);
insert into products (id, product_name, price) values (109, 'Car Vacuum', 6656.27);
insert into products (id, product_name, price) values (110, 'Desk Lamp with USB Port', 1140.43);
insert into products (id, product_name, price) values (111, 'Jump Rope with Counter', 6373.15);
insert into products (id, product_name, price) values (112, 'DIY Candle Kit', 1952.64);
insert into products (id, product_name, price) values (113, 'Set of Silicone Cooking Utensils', 270.13);
insert into products (id, product_name, price) values (114, 'Garlic Butter Sauce', 3960.52);
insert into products (id, product_name, price) values (115, 'Fall-Themed Table Runner', 7915.00);
insert into products (id, product_name, price) values (116, 'French Bread', 5652.76);
insert into products (id, product_name, price) values (117, 'Kids'' Science Experiment Kit', 5919.00);
insert into products (id, product_name, price) values (118, 'Peanut Butter Chocolate Clusters', 3303.54);
insert into products (id, product_name, price) values (119, 'Maple Bacon Potato Chips', 9678.46);
insert into products (id, product_name, price) values (120, 'Laptop Stand', 6045.08);
insert into products (id, product_name, price) values (121, 'Luxury Yoga Mat', 1222.13);
insert into products (id, product_name, price) values (122, 'Snack Container Set', 5184.56);
insert into products (id, product_name, price) values (123, 'LED Table Lamp', 1021.34);
insert into products (id, product_name, price) values (124, 'Folding Exercise Bike', 9065.83);
insert into products (id, product_name, price) values (125, 'Running Shorts', 3496.98);
insert into products (id, product_name, price) values (126, 'Electric Fondue Pot', 4320.48);
insert into products (id, product_name, price) values (127, 'Spaghetti Sauce', 1578.86);
insert into products (id, product_name, price) values (128, 'Adjustable Kneeling Pad', 9181.65);
insert into products (id, product_name, price) values (129, 'LED Makeup Mirror', 8352.61);
insert into products (id, product_name, price) values (130, 'Cheddar & Bacon Potato Skins', 144.73);
insert into products (id, product_name, price) values (131, 'Vegan Alfredo Sauce', 1120.82);
insert into products (id, product_name, price) values (132, 'Homemade Salsa', 8137.22);
insert into products (id, product_name, price) values (133, 'Magnetic Phone Car Mount', 9498.95);
insert into products (id, product_name, price) values (134, 'Party Mini Dress', 695.16);
insert into products (id, product_name, price) values (135, 'Portable Pet Bathing Tool', 8754.96);
insert into products (id, product_name, price) values (136, 'Training Soccer Ball', 2963.23);
insert into products (id, product_name, price) values (137, 'Tuna Fish (canned)', 268.37);
insert into products (id, product_name, price) values (138, 'Peach Slices (canned)', 236.76);
insert into products (id, product_name, price) values (139, 'Wooden Toy Train Set', 3344.93);
insert into products (id, product_name, price) values (140, 'Classic Caesar Salad Kit', 8895.62);
insert into products (id, product_name, price) values (141, 'Sweet Potato and Chickpea Bowl', 8793.73);
insert into products (id, product_name, price) values (142, 'Honeycrisp Apples', 6637.43);
insert into products (id, product_name, price) values (143, 'Rice Noodles', 7228.00);
insert into products (id, product_name, price) values (144, 'Tomato Basil Pasta Sauce', 3630.26);
insert into products (id, product_name, price) values (145, 'Apple Cinnamon Breakfast Muffins', 5215.50);
insert into products (id, product_name, price) values (146, 'Asian Stir-Fry Vegetables', 3732.35);
insert into products (id, product_name, price) values (147, 'Whole Grain Mustard', 895.05);
insert into products (id, product_name, price) values (148, 'Herb Drying Rack', 202.92);
insert into products (id, product_name, price) values (149, 'Whole Wheat Pasta', 9488.96);
insert into products (id, product_name, price) values (150, 'Canned Sardines', 1093.45);
insert into products (id, product_name, price) values (151, 'Digital Bullet Journal', 2769.11);
insert into products (id, product_name, price) values (152, 'Mesh Sports Leggings', 7924.23);
insert into products (id, product_name, price) values (153, 'Casual Sneakers', 1558.43);
insert into products (id, product_name, price) values (154, 'Smart Plug', 9485.02);
insert into products (id, product_name, price) values (155, 'Lemon Herb Grilled Chicken', 3639.46);
insert into products (id, product_name, price) values (156, 'Cereal Dispenser with Portion Control', 285.19);
insert into products (id, product_name, price) values (157, 'High-Waisted Skirt', 9260.93);
insert into products (id, product_name, price) values (158, 'Vintage Button-Down Shirt', 6458.32);
insert into products (id, product_name, price) values (159, 'Zesty Garlic Hummus', 4858.34);
insert into products (id, product_name, price) values (160, 'Maple Oatmeal', 6234.91);
insert into products (id, product_name, price) values (161, 'Leather Wallet', 9326.72);
insert into products (id, product_name, price) values (162, 'Organic Quinoa', 4296.21);
insert into products (id, product_name, price) values (163, 'Training Soccer Ball', 7939.91);
insert into products (id, product_name, price) values (164, 'Fashionable Fanny Pack', 523.09);
insert into products (id, product_name, price) values (165, 'Pineapple Coconut Rice Mix', 7134.05);
insert into products (id, product_name, price) values (166, 'Compact Pop-Up Tent', 3311.67);
insert into products (id, product_name, price) values (167, 'Vegetable Korma', 7857.78);
insert into products (id, product_name, price) values (168, 'Peanut Butter', 3061.69);
insert into products (id, product_name, price) values (169, 'Frozen Berry Blend', 7146.30);
insert into products (id, product_name, price) values (170, 'Cheesy Broccoli Soup Mix', 2967.18);
insert into products (id, product_name, price) values (171, 'Honey Mustard Chicken Breasts', 4707.58);
insert into products (id, product_name, price) values (172, 'Outdoor Fire Pit', 622.28);
insert into products (id, product_name, price) values (173, 'Essential Oils Diffuser Necklace', 8412.25);
insert into products (id, product_name, price) values (174, 'Electric Milk Frother', 8844.78);
insert into products (id, product_name, price) values (175, 'Organic Coconut Flour', 3090.77);
insert into products (id, product_name, price) values (176, 'Stylish Wireless Earbuds', 2877.42);
insert into products (id, product_name, price) values (177, 'Baby Monitor', 5097.58);
insert into products (id, product_name, price) values (178, 'Roasted Red Pepper Hummus', 5761.27);
insert into products (id, product_name, price) values (179, 'Wireless Charger', 6451.50);
insert into products (id, product_name, price) values (180, 'Red Lentils', 4566.41);
insert into products (id, product_name, price) values (181, 'Rechargeable Hand Warmer', 7902.96);
insert into products (id, product_name, price) values (182, 'Dog Car Seat Cover', 3921.69);
insert into products (id, product_name, price) values (183, 'Heavy Duty Gardening Tool Set', 865.86);
insert into products (id, product_name, price) values (184, 'Balsamic Salad Dressing', 4355.97);
insert into products (id, product_name, price) values (185, 'Overnight Duffle Bag', 3791.62);
insert into products (id, product_name, price) values (186, 'Garden Tool Belt', 3849.60);
insert into products (id, product_name, price) values (187, 'Yoga Strap', 5581.17);
insert into products (id, product_name, price) values (188, 'Mashed Sweet Potatoes', 497.13);
insert into products (id, product_name, price) values (189, 'Chili Beans in Sauce', 6416.50);
insert into products (id, product_name, price) values (190, 'Mango Chilli Sauce', 281.97);
insert into products (id, product_name, price) values (191, 'Smartphone Projector', 5272.66);
insert into products (id, product_name, price) values (192, 'Ricotta Cheese', 1025.25);
insert into products (id, product_name, price) values (193, 'Indoor Plants', 4688.56);
insert into products (id, product_name, price) values (194, 'Garlic and Herb Cream Cheese', 8500.55);
insert into products (id, product_name, price) values (195, 'Organic Almonds', 6141.05);
insert into products (id, product_name, price) values (196, 'Men''s Waterproof Hiking Boots', 3469.50);
insert into products (id, product_name, price) values (197, 'Basmati Rice', 6383.26);
insert into products (id, product_name, price) values (198, 'Carrot Sticks', 1895.22);
insert into products (id, product_name, price) values (199, 'Relaxed Fit Henley Shirt', 497.06);
insert into products (id, product_name, price) values (200, 'Electric Kettle', 9372.56);
insert into products (id, product_name, price) values (201, 'Creamy Coleslaw Mix', 6214.18);
insert into products (id, product_name, price) values (202, 'Chili Con Carne Mix', 7767.50);
insert into products (id, product_name, price) values (203, 'Kid''s Fruit Snacks', 8765.07);
insert into products (id, product_name, price) values (204, 'Dog Collar', 3366.55);
insert into products (id, product_name, price) values (205, 'Pet Water Fountain with Filtration', 7877.11);
insert into products (id, product_name, price) values (206, 'Pressure Cooker', 5411.65);
insert into products (id, product_name, price) values (207, 'Eco-Friendly Disposable Plates', 6296.86);
insert into products (id, product_name, price) values (208, 'Organic Green Tea', 2679.36);
insert into products (id, product_name, price) values (209, 'Brownie Bites', 9219.79);
insert into products (id, product_name, price) values (210, 'Self-Massaging Pillow', 1845.96);
insert into products (id, product_name, price) values (211, 'Belted Trench Coat', 2962.62);
insert into products (id, product_name, price) values (212, 'Savory Snack Mix', 8553.41);
insert into products (id, product_name, price) values (213, 'Compact Electric Kettle', 6498.96);
insert into products (id, product_name, price) values (214, 'Fruit Medley Juice', 8881.07);
insert into products (id, product_name, price) values (215, 'Oats', 7116.07);
insert into products (id, product_name, price) values (216, 'Travel Pillow with Memory Foam', 2835.36);
insert into products (id, product_name, price) values (217, 'Adjustable Height Standing Desk Converter', 9768.88);
insert into products (id, product_name, price) values (218, 'Graphic Tee', 173.31);
insert into products (id, product_name, price) values (219, 'Honey Mustard Chicken Breasts', 3927.69);
insert into products (id, product_name, price) values (220, 'Herbed Goat Cheese', 7906.81);
insert into products (id, product_name, price) values (221, 'Ceramic Bakeware Set', 362.91);
insert into products (id, product_name, price) values (222, 'Organic Brown Sugar', 4270.55);
insert into products (id, product_name, price) values (223, 'Spicy Chicken Wings', 501.35);
insert into products (id, product_name, price) values (224, 'Emergency Preparedness Kit', 9104.04);
insert into products (id, product_name, price) values (225, 'Honeycrisp Apples', 5174.23);
insert into products (id, product_name, price) values (226, 'Fitness Tracker Band', 1656.96);
insert into products (id, product_name, price) values (227, 'Bamboo Cutting Board', 8442.69);
insert into products (id, product_name, price) values (228, 'Brown Rice', 1859.02);
insert into products (id, product_name, price) values (229, 'Portable Camping Shower', 2322.62);
insert into products (id, product_name, price) values (230, 'Comfort Flats', 8311.11);
insert into products (id, product_name, price) values (231, 'Adjustable Standing Desk', 5570.71);
insert into products (id, product_name, price) values (232, 'Frozen Fruit Medley', 8322.24);
insert into products (id, product_name, price) values (233, 'Travel Beach Blanket', 7172.79);
insert into products (id, product_name, price) values (234, 'Decorative Throw Pillows', 5612.56);
insert into products (id, product_name, price) values (235, 'French Onion Dip', 9260.96);
insert into products (id, product_name, price) values (236, 'Cinnamon Roll Dough', 2531.13);
insert into products (id, product_name, price) values (237, 'Almond Flour Bread Mix', 3192.98);
insert into products (id, product_name, price) values (238, 'Kale & Quinoa Salad Mix', 7494.49);
insert into products (id, product_name, price) values (239, 'Frozen Chicken Nuggets', 4943.42);
insert into products (id, product_name, price) values (240, 'Wireless Mouse', 9893.55);
insert into products (id, product_name, price) values (241, 'Leather Notebook Cover', 7863.08);
insert into products (id, product_name, price) values (242, 'Collapsible Camping Cup', 8250.37);
insert into products (id, product_name, price) values (243, 'Aged White Cheddar Popcorn', 5579.22);
insert into products (id, product_name, price) values (244, 'Smart Light Switch', 7064.77);
insert into products (id, product_name, price) values (245, 'Savory Trail Mix', 4685.99);
insert into products (id, product_name, price) values (246, 'Smoked Salmon', 1896.14);
insert into products (id, product_name, price) values (247, 'Teriyaki Chicken Stir-Fry', 8447.33);
insert into products (id, product_name, price) values (248, 'Wireless Game Controller', 2102.92);
insert into products (id, product_name, price) values (249, 'Ceramic Bakeware Set', 9881.73);
insert into products (id, product_name, price) values (250, 'Elegant Maxi Skirt', 3092.00);
insert into products (id, product_name, price) values (251, 'Wall Calendar', 6074.62);
insert into products (id, product_name, price) values (252, 'Folding Pocket Knife', 1830.56);
insert into products (id, product_name, price) values (253, 'Herbal Tea Set', 959.12);
insert into products (id, product_name, price) values (254, 'Organic Granola Cereal', 6685.78);
insert into products (id, product_name, price) values (255, 'Personalized Pet ID Tags', 3556.68);
insert into products (id, product_name, price) values (256, 'Cranberry Juice', 943.37);
insert into products (id, product_name, price) values (257, 'Organic Green Lentils', 5741.46);
insert into products (id, product_name, price) values (258, 'Fitness Mat', 3275.03);
insert into products (id, product_name, price) values (259, 'Wall Art Stickers', 3070.56);
insert into products (id, product_name, price) values (260, 'Rainbow Veggie Chips', 6718.10);
insert into products (id, product_name, price) values (261, 'Smoked Gouda Cheese', 7691.06);
insert into products (id, product_name, price) values (262, 'Black Bean Soup', 411.66);
insert into products (id, product_name, price) values (263, 'Pet Hair Vacuum Attachment', 1490.66);
insert into products (id, product_name, price) values (264, 'Blueberry Chia Jam', 1800.23);
insert into products (id, product_name, price) values (265, 'Weighted Jump Rope with Counter', 8234.24);
insert into products (id, product_name, price) values (266, 'Cauliflower Rice Stir-Fry', 5388.31);
insert into products (id, product_name, price) values (267, 'Lemon Lime Sparkling Water', 9500.80);
insert into products (id, product_name, price) values (268, 'Potting Soil', 2757.40);
insert into products (id, product_name, price) values (269, 'Smart Plug', 2357.29);
insert into products (id, product_name, price) values (270, 'Chickpea Pasta', 7670.71);
insert into products (id, product_name, price) values (271, 'Wall Art Stickers', 7235.49);
insert into products (id, product_name, price) values (272, 'Margherita Pizza', 5719.26);
insert into products (id, product_name, price) values (273, 'Electric Food Slicer', 9668.14);
insert into products (id, product_name, price) values (274, 'Egg Noodles', 6499.82);
insert into products (id, product_name, price) values (275, 'Frozen Broccoli', 9890.35);
insert into products (id, product_name, price) values (276, 'Laptop Stand', 6952.46);
insert into products (id, product_name, price) values (277, 'LED Canopy Lights', 9067.71);
insert into products (id, product_name, price) values (278, 'Pet First Aid Kit', 424.87);
insert into products (id, product_name, price) values (279, 'Adjustable Dumbbells', 7107.14);
insert into products (id, product_name, price) values (280, 'Silicone Wine Glasses', 9003.37);
insert into products (id, product_name, price) values (281, 'Gaming Headset', 731.06);
insert into products (id, product_name, price) values (282, 'Pet Waterer with Filtration', 3717.69);
insert into products (id, product_name, price) values (283, 'Portable Jump Starter', 5780.07);
insert into products (id, product_name, price) values (284, 'Spicy BBQ Sauce', 820.39);
insert into products (id, product_name, price) values (285, 'Sweet Corn', 2257.18);
insert into products (id, product_name, price) values (286, 'Balsamic Salad Dressing', 8793.46);
insert into products (id, product_name, price) values (287, 'Pet Food Storage Container', 4360.27);
insert into products (id, product_name, price) values (288, 'Electric Heat Pad', 8626.92);
insert into products (id, product_name, price) values (289, 'Outdoor Mosquito Repellent Lantern', 649.78);
insert into products (id, product_name, price) values (290, 'Athletic Compression Tights', 2439.89);
insert into products (id, product_name, price) values (291, 'Kale Chips', 767.07);
insert into products (id, product_name, price) values (292, 'Hydration Backpack', 8753.95);
insert into products (id, product_name, price) values (293, 'Garlic Parmesan Roasted Nuts', 1806.96);
insert into products (id, product_name, price) values (294, 'LED Strip Lights Kit', 8304.62);
insert into products (id, product_name, price) values (295, 'Foam Roller for Muscle Recovery', 3098.42);
insert into products (id, product_name, price) values (296, 'Fitness Jump Box', 6161.30);
insert into products (id, product_name, price) values (297, 'Portable USB-C Monitor', 4998.10);
insert into products (id, product_name, price) values (298, 'Mini Projector for Smartphones', 4462.18);
insert into products (id, product_name, price) values (299, 'Electric Toothbrush Holder', 3327.80);
insert into products (id, product_name, price) values (300, 'Portable Projector', 4261.35);
insert into products (id, product_name, price) values (301, 'Classic Bagels', 4712.14);
insert into products (id, product_name, price) values (302, 'Miso Soup Starter', 8755.29);
insert into products (id, product_name, price) values (303, 'Fleece Hoodie', 4445.19);
insert into products (id, product_name, price) values (304, 'Pineapple Salsa', 3248.73);
insert into products (id, product_name, price) values (305, 'Faux Fur Throw Blanket', 1061.20);
insert into products (id, product_name, price) values (306, 'Pet Hair Vacuum Cleaner Attachment', 5064.55);
insert into products (id, product_name, price) values (307, 'Lemon Lime Sparkling Water', 1186.78);
insert into products (id, product_name, price) values (308, 'Wireless Induction Charger', 581.24);
insert into products (id, product_name, price) values (309, 'Smart Home Hub', 4405.76);
insert into products (id, product_name, price) values (310, 'Chicken Broth', 7364.51);
insert into products (id, product_name, price) values (311, 'Silicone Baking Cups', 5773.93);
insert into products (id, product_name, price) values (312, 'Scented Soy Candles', 9236.75);
insert into products (id, product_name, price) values (313, 'Vegetarian Pizza', 9176.37);
insert into products (id, product_name, price) values (314, 'Cinnamon Spiced Almonds', 1215.96);
insert into products (id, product_name, price) values (315, 'Fresh Basil Pesto', 5811.82);
insert into products (id, product_name, price) values (316, 'Classic Leather Wallet', 3676.12);
insert into products (id, product_name, price) values (317, 'Stainless Steel Water Bottle', 6226.42);
insert into products (id, product_name, price) values (318, 'High-Speed Blender', 8022.98);
insert into products (id, product_name, price) values (319, 'Digital Photo Frame', 899.79);
insert into products (id, product_name, price) values (320, 'Smartphone Holder for Car', 8447.93);
insert into products (id, product_name, price) values (321, 'Smartwatch', 9317.49);
insert into products (id, product_name, price) values (322, 'Satin Slip Dress', 3387.83);
insert into products (id, product_name, price) values (323, 'Fleece Throw Blanket', 7433.42);
insert into products (id, product_name, price) values (324, 'Memory Card', 2739.15);
insert into products (id, product_name, price) values (325, 'Adjustable Kneeling Pad', 2942.12);
insert into products (id, product_name, price) values (326, 'Garden Vegetable Soup', 8447.70);
insert into products (id, product_name, price) values (327, 'Sesame Ginger Dressing', 5783.03);
insert into products (id, product_name, price) values (328, 'Strawberry Banana Smoothie Pack', 4122.53);
insert into products (id, product_name, price) values (329, 'Interactive Robot Toy', 3612.23);
insert into products (id, product_name, price) values (330, 'Lemon Herb Grilled Chicken', 4396.98);
insert into products (id, product_name, price) values (331, 'Italian Sausage Links', 1905.83);
insert into products (id, product_name, price) values (332, 'Kombucha Drink', 1582.09);
insert into products (id, product_name, price) values (333, 'Jasmine Rice', 3706.71);
insert into products (id, product_name, price) values (334, 'Basketball', 598.14);
insert into products (id, product_name, price) values (335, 'Reflective Safety Vest', 6494.47);
insert into products (id, product_name, price) values (336, 'Magnetic Spice Jars', 9609.53);
insert into products (id, product_name, price) values (337, 'Air Fryer', 270.62);
insert into products (id, product_name, price) values (338, 'Children''s Musical Instrument Set', 9330.56);
insert into products (id, product_name, price) values (339, 'Solar Power Bank', 6983.30);
insert into products (id, product_name, price) values (340, 'Himalayan Pink Salt', 656.09);
insert into products (id, product_name, price) values (341, 'Breathable Face Mask Set', 3130.39);
insert into products (id, product_name, price) values (342, 'Vegetable Spiralizer', 7413.68);
insert into products (id, product_name, price) values (343, 'Compact Refrigerator', 1210.44);
insert into products (id, product_name, price) values (344, 'Digital Thermostat', 7537.99);
insert into products (id, product_name, price) values (345, 'Microfiber Cleaning Cloth Set', 8082.45);
insert into products (id, product_name, price) values (346, 'Infrared Space Heater', 5747.21);
insert into products (id, product_name, price) values (347, 'Garden Vegetable Soup', 3801.77);
insert into products (id, product_name, price) values (348, 'Bluetooth Car Adapter', 6243.08);
insert into products (id, product_name, price) values (349, 'Poppy Seed Dressing', 1282.04);
insert into products (id, product_name, price) values (350, 'Wrist Support Brace', 7682.51);
insert into products (id, product_name, price) values (351, 'Kids'' Science Experiment Kit', 8363.23);
insert into products (id, product_name, price) values (352, 'Noise-Canceling Earbuds', 445.97);
insert into products (id, product_name, price) values (353, 'Cucumber Relish', 4198.24);
insert into products (id, product_name, price) values (354, 'Tabletop Fire Pit', 4644.26);
insert into products (id, product_name, price) values (355, 'Honey Almond Granola Bars', 9357.27);
insert into products (id, product_name, price) values (356, 'Savory Breakfast Sausage', 3492.74);
insert into products (id, product_name, price) values (357, 'Flavored Rice Cakes', 4154.27);
insert into products (id, product_name, price) values (358, 'Electric Ice Cream Maker', 9422.70);
insert into products (id, product_name, price) values (359, 'Kids'' STEM Robotics Kit', 9322.31);
insert into products (id, product_name, price) values (360, 'Eco-Friendly Cleaning Cloths', 5450.14);
insert into products (id, product_name, price) values (361, 'Whole Roasted Chicken', 2271.80);
insert into products (id, product_name, price) values (362, 'Pepperoni Pizza Roll-Ups', 1982.57);
insert into products (id, product_name, price) values (363, 'Roasted Red Pepper Dip', 9293.12);
insert into products (id, product_name, price) values (364, 'Black Bean Spaghetti', 8162.76);
insert into products (id, product_name, price) values (365, 'Apple Cinnamon Granola', 6482.40);
insert into products (id, product_name, price) values (366, 'Golf Polo Shirt', 6191.66);
insert into products (id, product_name, price) values (367, 'Herbed Couscous', 198.73);
insert into products (id, product_name, price) values (368, 'Pumpkin Waffles', 6612.58);
insert into products (id, product_name, price) values (369, 'Luxury Bath Robe', 4137.10);
insert into products (id, product_name, price) values (370, 'Electric Heat Press Machine', 9512.95);
insert into products (id, product_name, price) values (371, 'Sweet Potato Mash', 8245.69);
insert into products (id, product_name, price) values (372, 'Cold Brew Coffee Maker', 4415.96);
insert into products (id, product_name, price) values (373, 'Vegetable Pizza Rolls', 4469.03);
insert into products (id, product_name, price) values (374, 'Measuring Cups Set', 8479.31);
insert into products (id, product_name, price) values (375, 'Chocolate Coconut Granola', 4210.36);
insert into products (id, product_name, price) values (376, 'Dark Chocolate Covered Raisins', 3660.06);
insert into products (id, product_name, price) values (377, 'Reusable Snack Bags', 346.44);
insert into products (id, product_name, price) values (378, 'Himalayan Salt Grinder', 4955.37);
insert into products (id, product_name, price) values (379, 'Infrared Thermometer', 8330.66);
insert into products (id, product_name, price) values (380, 'Eco-Friendly Stainless Steel Straws', 4977.76);
insert into products (id, product_name, price) values (381, 'LED Disco Ball Light', 8457.64);
insert into products (id, product_name, price) values (382, 'Cordless Electric Screwdriver', 8216.49);
insert into products (id, product_name, price) values (383, 'Cranberry Juice', 1841.27);
insert into products (id, product_name, price) values (384, 'Wireless Earbuds', 9163.10);
insert into products (id, product_name, price) values (385, 'Beef Tacos', 5706.98);
insert into products (id, product_name, price) values (386, 'Coconut Water', 7176.41);
insert into products (id, product_name, price) values (387, 'Cork Yoga Mat', 550.02);
insert into products (id, product_name, price) values (388, 'Travel Pillow', 4223.69);
insert into products (id, product_name, price) values (389, 'Italian Marinara Sauce', 93.57);
insert into products (id, product_name, price) values (390, 'Frozen Broccoli', 2889.81);
insert into products (id, product_name, price) values (391, 'Skincare Fridge', 9362.25);
insert into products (id, product_name, price) values (392, 'Zesty Garlic Marinade', 7777.78);
insert into products (id, product_name, price) values (393, 'Italian Herbal Seasoning', 6758.56);
insert into products (id, product_name, price) values (394, 'Sweet Cherry Tomatoes', 5621.34);
insert into products (id, product_name, price) values (395, 'Sourdough Bread', 7789.23);
insert into products (id, product_name, price) values (396, 'Honey Roasted Chickpeas', 5520.49);
insert into products (id, product_name, price) values (397, 'Nutty Granola Clusters', 5413.07);
insert into products (id, product_name, price) values (398, 'Collapsible Water Bottle', 612.18);
insert into products (id, product_name, price) values (399, 'Magnetic Phone Case', 2179.61);
insert into products (id, product_name, price) values (400, 'Rainbow Veggie Chips', 3218.33);
insert into products (id, product_name, price) values (401, 'Whole Roasted Chicken', 7910.65);
insert into products (id, product_name, price) values (402, 'Red Lentils', 2305.63);
insert into products (id, product_name, price) values (403, 'Free-Range Eggs', 3975.18);
insert into products (id, product_name, price) values (404, 'Spicy Thai Noodles', 3721.52);
insert into products (id, product_name, price) values (405, 'Wireless Car Charger', 559.07);
insert into products (id, product_name, price) values (406, 'Luxury Bath Robe', 7815.22);
insert into products (id, product_name, price) values (407, 'Vegetable Spring Rolls', 3338.36);
insert into products (id, product_name, price) values (408, 'Asian Salad Mix', 3495.35);
insert into products (id, product_name, price) values (409, 'Organic Quinoa Salad', 9995.55);
insert into products (id, product_name, price) values (410, 'Pasta Primavera', 3186.63);
insert into products (id, product_name, price) values (411, 'Window A/C Unit', 9801.51);
insert into products (id, product_name, price) values (412, 'Portable Grill Cover', 8500.44);
insert into products (id, product_name, price) values (413, 'Fitness Tracker with Heart Rate Monitor', 3654.93);
insert into products (id, product_name, price) values (414, 'Hand Mixer', 8724.22);
insert into products (id, product_name, price) values (415, 'Canvas Tote Bag', 838.43);
insert into products (id, product_name, price) values (416, 'Elegant Maxi Skirt', 5928.39);
insert into products (id, product_name, price) values (417, 'Sweet BBQ Dipping Sauce', 4531.95);
insert into products (id, product_name, price) values (418, 'Car Sunshade', 6490.02);
insert into products (id, product_name, price) values (419, 'Honeycrisp Apple Chips', 3755.86);
insert into products (id, product_name, price) values (420, 'Sweet Potato Chips', 3190.23);
insert into products (id, product_name, price) values (421, 'Lemon Garlic Marinade', 3882.04);
insert into products (id, product_name, price) values (422, 'Flavored Instant Oatmeal', 6371.73);
insert into products (id, product_name, price) values (423, 'Herb Garlic Butter', 6523.10);
insert into products (id, product_name, price) values (424, 'Balsamic Fig Dressing', 7748.62);
insert into products (id, product_name, price) values (425, 'Mini Hand Gesture Drone', 4164.68);
insert into products (id, product_name, price) values (426, 'Weighted Jump Rope with Counter', 5581.18);
insert into products (id, product_name, price) values (427, 'Tomatillo Salsa', 4112.93);
insert into products (id, product_name, price) values (428, 'Truffle Parmesan Fries', 2761.97);
insert into products (id, product_name, price) values (429, 'Silicone Baking Cups', 5452.97);
insert into products (id, product_name, price) values (430, 'Slingback Sandals', 2198.17);
insert into products (id, product_name, price) values (431, 'Trendy Bomber Jacket', 4174.50);
insert into products (id, product_name, price) values (432, 'Green Smoothie Mix', 3411.48);
insert into products (id, product_name, price) values (433, 'Italian Breadsticks', 7123.15);
insert into products (id, product_name, price) values (434, 'Sweet Potato & Kale Hash', 308.66);
insert into products (id, product_name, price) values (435, 'Travel Document Organizer', 5959.00);
insert into products (id, product_name, price) values (436, 'Honey Garlic Chicken', 9978.56);
insert into products (id, product_name, price) values (437, 'Almond Butter Crunch Bar', 8611.55);
insert into products (id, product_name, price) values (438, 'Fitness Tracker with Heart Rate Monitor', 3122.43);
insert into products (id, product_name, price) values (439, 'USB Flash Drive', 275.44);
insert into products (id, product_name, price) values (440, 'Smartphone UV Sanitizer', 5476.16);
insert into products (id, product_name, price) values (441, 'Leek and Potato Soup', 2235.51);
insert into products (id, product_name, price) values (442, 'LED Desk Lamp with USB Charging Port', 8354.97);
insert into products (id, product_name, price) values (443, 'Luxe Velvet Blazer', 4779.32);
insert into products (id, product_name, price) values (444, 'Dog Training Whistle', 5958.46);
insert into products (id, product_name, price) values (445, 'LED Table Lamp', 2034.37);
insert into products (id, product_name, price) values (446, 'Lemon Garlic Marinade', 4370.58);
insert into products (id, product_name, price) values (447, 'Garden Tool Belt', 8953.63);
insert into products (id, product_name, price) values (448, 'Fitness Tracker with Heart Rate Monitor', 8230.78);
insert into products (id, product_name, price) values (449, 'Sweet Potato Mash', 6339.47);
insert into products (id, product_name, price) values (450, 'Buttermilk Pancakes', 813.71);
insert into products (id, product_name, price) values (451, 'Mediterranean Couscous', 4556.04);
insert into products (id, product_name, price) values (452, 'Belted Trench Coat', 6474.31);
insert into products (id, product_name, price) values (453, 'Nutty Quinoa Salad', 3504.47);
insert into products (id, product_name, price) values (454, 'Pasta Primavera Kit', 8736.40);
insert into products (id, product_name, price) values (455, 'Tahini', 9148.64);
insert into products (id, product_name, price) values (456, 'Fishing Tackle Box', 2068.80);
insert into products (id, product_name, price) values (457, 'Chipotle Sauce', 8287.29);
insert into products (id, product_name, price) values (458, 'Cinnamon Sugar Mix', 3277.39);
insert into products (id, product_name, price) values (459, 'Sweet BBQ Dipping Sauce', 7305.01);
insert into products (id, product_name, price) values (460, 'Sustainable Wooden Toys', 9510.69);
insert into products (id, product_name, price) values (461, 'Peach Halves (canned)', 4422.23);
insert into products (id, product_name, price) values (462, 'Children''s Musical Instrument Set', 3539.01);
insert into products (id, product_name, price) values (463, 'Sous Vide Cooker', 4651.49);
insert into products (id, product_name, price) values (464, 'Rice Pudding', 9111.37);
insert into products (id, product_name, price) values (465, 'Adjustable Bar Stools', 2121.07);
insert into products (id, product_name, price) values (466, 'Vegetable Fried Rice Mix', 8101.12);
insert into products (id, product_name, price) values (467, 'Portable Bluetooth Headphones', 556.18);
insert into products (id, product_name, price) values (468, 'Cable Knit Beanie', 3184.99);
insert into products (id, product_name, price) values (469, 'Smoked Salmon', 5720.95);
insert into products (id, product_name, price) values (470, 'Smart Water Bottle with Hydration Reminder', 1503.11);
insert into products (id, product_name, price) values (471, 'Sweet Corn Fritters', 1907.96);
insert into products (id, product_name, price) values (472, 'Classic BBQ Sauce', 29.28);
insert into products (id, product_name, price) values (473, 'Elegant Maxi Skirt', 5548.81);
insert into products (id, product_name, price) values (474, 'Garden Hoses with Expandable Features', 382.69);
insert into products (id, product_name, price) values (475, 'Chili Con Carne Mix', 9692.54);
insert into products (id, product_name, price) values (476, 'Honeycrisp Apples', 2030.07);
insert into products (id, product_name, price) values (477, 'Sliced Olives', 8574.41);
insert into products (id, product_name, price) values (478, 'Foldable Yoga Mat', 7141.54);
insert into products (id, product_name, price) values (479, 'Carrot and Celery Sticks', 4706.26);
insert into products (id, product_name, price) values (480, 'Ethically-Sourced Coffee Beans', 3894.21);
insert into products (id, product_name, price) values (481, 'Coconut Yogurt', 2866.79);
insert into products (id, product_name, price) values (482, 'Fishing Tackle Box', 8977.95);
insert into products (id, product_name, price) values (483, 'Spicy Kimchi', 1366.96);
insert into products (id, product_name, price) values (484, 'Floral Wrap Top', 1018.01);
insert into products (id, product_name, price) values (485, 'Mini Cordless Vacuum Cleaner', 8386.47);
insert into products (id, product_name, price) values (486, 'Pumpkin Spice Cookies', 5938.67);
insert into products (id, product_name, price) values (487, 'Aeropress Coffee Maker', 8356.82);
insert into products (id, product_name, price) values (488, 'Radish Chips', 8099.86);
insert into products (id, product_name, price) values (489, 'Honey Garlic Shrimp', 6424.57);
insert into products (id, product_name, price) values (490, 'Chocolate Chip Cookie Mix', 6469.46);
insert into products (id, product_name, price) values (491, 'Foot Spa Bath Massager', 8193.44);
insert into products (id, product_name, price) values (492, 'Miso Soup Starter', 5829.48);
insert into products (id, product_name, price) values (493, 'Smoked Gouda Cheese', 7451.34);
insert into products (id, product_name, price) values (494, 'Tomato Basil Pasta Sauce', 7378.22);
insert into products (id, product_name, price) values (495, 'Luxury Bathrobe', 7625.12);
insert into products (id, product_name, price) values (496, 'Italian Sausage Links', 180.72);
insert into products (id, product_name, price) values (497, 'Fishing Rod', 904.88);
insert into products (id, product_name, price) values (498, 'Vegetable Chips', 7447.19);
insert into products (id, product_name, price) values (499, 'Beef Chili', 2863.04);
insert into products (id, product_name, price) values (500, 'Instant Read Meat Thermometer', 8061.06);
insert into products (id, product_name, price) values (501, 'Oven-Baked Cheese Crisps', 5342.13);
insert into products (id, product_name, price) values (502, 'Collapsible Pet Dog Bowl', 4691.29);
insert into products (id, product_name, price) values (503, 'Spinach and Feta Wraps', 4308.11);
insert into products (id, product_name, price) values (504, 'Thai Coconut Curry Sauce', 2371.82);
insert into products (id, product_name, price) values (505, 'Antique Style Clock', 8079.87);
insert into products (id, product_name, price) values (506, 'Sustainable Wooden Toys', 5418.27);
insert into products (id, product_name, price) values (507, 'Italian Marinara Sauce', 1325.25);
insert into products (id, product_name, price) values (508, 'Pumpkin Pancake Mix', 1674.94);
insert into products (id, product_name, price) values (509, 'Herbal Tea Set', 5341.17);
insert into products (id, product_name, price) values (510, 'Ice Cube Tray with Lid', 3701.32);
insert into products (id, product_name, price) values (511, 'Pumpkin Spice Creamer', 7727.58);
insert into products (id, product_name, price) values (512, 'Coconut Water', 8166.10);
insert into products (id, product_name, price) values (513, 'Whole Wheat Pasta', 7038.97);
insert into products (id, product_name, price) values (514, 'Kettle BBQ Grill', 3208.78);
insert into products (id, product_name, price) values (515, 'Cinnamon Roll Dough', 9804.49);
insert into products (id, product_name, price) values (516, 'Smart LED Light Strip', 9860.34);
insert into products (id, product_name, price) values (517, 'Air Purifier', 1322.94);
insert into products (id, product_name, price) values (518, 'Digital Food Thermometer', 3116.88);
insert into products (id, product_name, price) values (519, 'Electric Stool Heater', 3427.29);
insert into products (id, product_name, price) values (520, 'Spicy Hummus', 4791.98);
insert into products (id, product_name, price) values (521, 'Asian Stir-Fry Kit', 7035.82);
insert into products (id, product_name, price) values (522, 'Smartwatch', 7138.59);
insert into products (id, product_name, price) values (523, 'Radish Chips', 3860.61);
insert into products (id, product_name, price) values (524, 'Ice Cream', 2882.30);
insert into products (id, product_name, price) values (525, 'Dish Soap Dispenser', 5859.58);
insert into products (id, product_name, price) values (526, 'Stylish Wide-Leg Trousers', 6459.00);
insert into products (id, product_name, price) values (527, 'Compact Pop-Up Tent', 1591.75);
insert into products (id, product_name, price) values (528, 'Wireless Security Camera', 4541.47);
insert into products (id, product_name, price) values (529, 'Plant-Based Meal Prep Containers', 9559.77);
insert into products (id, product_name, price) values (530, 'Stainless Steel Mixing Bowls', 9843.02);
insert into products (id, product_name, price) values (531, 'Digital Meat Thermometer', 5497.79);
insert into products (id, product_name, price) values (532, 'Aeropress Coffee Maker', 7985.30);
insert into products (id, product_name, price) values (533, 'Carrot and Celery Sticks', 7169.46);
insert into products (id, product_name, price) values (534, 'Ranch Dressing', 6361.94);
insert into products (id, product_name, price) values (535, 'Artisan Cornbread Mix', 2401.41);
insert into products (id, product_name, price) values (536, 'Bike Helmet', 1699.96);
insert into products (id, product_name, price) values (537, 'Asian Salad Mix', 1108.88);
insert into products (id, product_name, price) values (538, 'Organic Brown Rice Cakes', 2451.41);
insert into products (id, product_name, price) values (539, 'Elegant Lace Dress', 3324.67);
insert into products (id, product_name, price) values (540, 'Cotton Basic Tank', 7518.58);
insert into products (id, product_name, price) values (541, 'Carrot Ginger Soup', 1799.90);
insert into products (id, product_name, price) values (542, 'Adjustable Laptop Desk', 7880.30);
insert into products (id, product_name, price) values (543, 'Cocktail Shaker and Mixing Glass Set', 8053.39);
insert into products (id, product_name, price) values (544, 'Two-Tone Windbreaker', 5427.76);
insert into products (id, product_name, price) values (545, 'Floral Summer Dress', 5693.00);
insert into products (id, product_name, price) values (546, 'Survival Gear Kit', 6418.88);
insert into products (id, product_name, price) values (547, 'Infrared Thermometer', 8045.51);
insert into products (id, product_name, price) values (548, 'Peanut Butter Chocolate Clusters', 1008.35);
insert into products (id, product_name, price) values (549, 'Butternut Squash Ravioli', 8448.51);
insert into products (id, product_name, price) values (550, 'Coffee Making Kit', 7380.11);
insert into products (id, product_name, price) values (551, 'Drone', 8526.11);
insert into products (id, product_name, price) values (552, 'Vanilla Protein Powder', 9922.66);
insert into products (id, product_name, price) values (553, 'Fruit Infuser Water Bottle', 3065.79);
insert into products (id, product_name, price) values (554, 'Banana Nut Oatmeal Cups', 5768.74);
insert into products (id, product_name, price) values (555, 'Low-Fat Yogurt', 3618.36);
insert into products (id, product_name, price) values (556, 'Beef Stew Meat', 2630.60);
insert into products (id, product_name, price) values (557, 'Whisk Set', 6416.07);
insert into products (id, product_name, price) values (558, 'Organic Honeycrisp Apples', 4713.66);
insert into products (id, product_name, price) values (559, 'Quinoa & Black Bean Salad', 6519.36);
insert into products (id, product_name, price) values (560, 'Rice Cakes', 9651.61);
insert into products (id, product_name, price) values (561, 'Running Shorts', 4688.90);
insert into products (id, product_name, price) values (562, 'Pine Nuts', 8567.05);
insert into products (id, product_name, price) values (563, 'Buffalo Style Cauliflower Bites', 2108.85);
insert into products (id, product_name, price) values (564, 'Non-Toxic Concrete Sealer', 2914.80);
insert into products (id, product_name, price) values (565, 'Maple Cinnamon Granola Bars', 889.83);
insert into products (id, product_name, price) values (566, 'Pineapple Coconut Yogurt', 6150.37);
insert into products (id, product_name, price) values (567, 'Classic Bagels', 5466.87);
insert into products (id, product_name, price) values (568, 'Eco-Friendly Beeswax Wraps', 5153.37);
insert into products (id, product_name, price) values (569, 'Spicy Thai Noodles', 8313.95);
insert into products (id, product_name, price) values (570, 'Workstation Laptop Stand', 7299.04);
insert into products (id, product_name, price) values (571, 'Rechargeable Battery Organizer', 8593.35);
insert into products (id, product_name, price) values (572, 'Raisin Cinnamon Granola', 6255.43);
insert into products (id, product_name, price) values (573, 'Shoe Organizer', 3444.84);
insert into products (id, product_name, price) values (574, 'Watercolor Brush Pens', 8664.80);
insert into products (id, product_name, price) values (575, 'Thai Basil Fried Rice', 8703.50);
insert into products (id, product_name, price) values (576, 'Organic Coconut Oil', 8815.72);
insert into products (id, product_name, price) values (577, 'Silicone Baking Mats', 9958.16);
insert into products (id, product_name, price) values (578, 'Slim Wallet', 9346.61);
insert into products (id, product_name, price) values (579, 'Travel Jewelry Case', 7718.46);
insert into products (id, product_name, price) values (580, 'Tahini', 2016.27);
insert into products (id, product_name, price) values (581, 'Maxi Wrap Dress', 9953.30);
insert into products (id, product_name, price) values (582, 'Travel Size Toiletry Bottles', 5124.42);
insert into products (id, product_name, price) values (583, 'Wine Decanter', 2497.23);
insert into products (id, product_name, price) values (584, 'Decorative LED Neon Sign', 5747.74);
insert into products (id, product_name, price) values (585, 'Elegant Maxi Skirt', 6215.68);
insert into products (id, product_name, price) values (586, 'Plaid Flannel Shirt', 4658.54);
insert into products (id, product_name, price) values (587, 'Maple Almond Granola', 520.12);
insert into products (id, product_name, price) values (588, 'Chocolate Covered Pretzels', 8508.86);
insert into products (id, product_name, price) values (589, 'Buffalo Stilton Cheese', 495.27);
insert into products (id, product_name, price) values (590, 'Sweet Potato Fries', 1177.26);
insert into products (id, product_name, price) values (591, 'Faux Fur Coat', 1242.25);
insert into products (id, product_name, price) values (592, 'Ethical Wool Scarf', 7812.12);
insert into products (id, product_name, price) values (593, 'Portable Air Compressor', 6451.42);
insert into products (id, product_name, price) values (594, 'Almond Flour Bread Mix', 5218.99);
insert into products (id, product_name, price) values (595, 'Tortilla Chips', 1672.81);
insert into products (id, product_name, price) values (596, 'Electric Pressure Washer', 2115.55);
insert into products (id, product_name, price) values (597, 'Relaxed Fit Henley Shirt', 6253.98);
insert into products (id, product_name, price) values (598, 'Thai Basil Fried Rice', 8513.47);
insert into products (id, product_name, price) values (599, 'Craft Beer Mustard', 1745.10);
insert into products (id, product_name, price) values (600, 'Sesame Oil', 7810.90);
insert into products (id, product_name, price) values (601, 'USB Flash Drive', 7849.09);
insert into products (id, product_name, price) values (602, 'Relaxed Fit Henley Shirt', 8563.28);
insert into products (id, product_name, price) values (603, 'Folding Pocket Knife', 6258.43);
insert into products (id, product_name, price) values (604, 'Almond Flour Biscuits', 8053.74);
insert into products (id, product_name, price) values (605, 'Peach Green Tea', 8102.26);
insert into products (id, product_name, price) values (606, 'Lentils', 7042.59);
insert into products (id, product_name, price) values (607, 'Chocolate Hazelnut Spread', 2357.71);
insert into products (id, product_name, price) values (608, 'Instant Read Meat Thermometer', 7499.30);
insert into products (id, product_name, price) values (609, 'Rainbow Veggie Chips', 5192.35);
insert into products (id, product_name, price) values (610, 'Faux Fur Coat', 2673.17);
insert into products (id, product_name, price) values (611, 'Jump Rope with Counter', 2355.03);
insert into products (id, product_name, price) values (612, 'Multi-Functional Rice Cooker', 962.22);
insert into products (id, product_name, price) values (613, 'Smartphone Car Mount with Wireless Charging', 1525.24);
insert into products (id, product_name, price) values (614, 'Peach Mango Smoothie', 5728.49);
insert into products (id, product_name, price) values (615, 'Peach Fruit Cups', 908.00);
insert into products (id, product_name, price) values (616, 'Marinara Parmesan Baked Ziti', 2186.55);
insert into products (id, product_name, price) values (617, 'Almond Coconut Granola', 4128.52);
insert into products (id, product_name, price) values (618, 'Chocolate Almond Milk', 3359.69);
insert into products (id, product_name, price) values (619, 'Customizable Photo Calendar', 927.37);
insert into products (id, product_name, price) values (620, 'Weighted Jump Rope', 2493.35);
insert into products (id, product_name, price) values (621, 'Wireless Security Camera', 2312.78);
insert into products (id, product_name, price) values (622, 'Shatterproof Wine Glasses', 3445.18);
insert into products (id, product_name, price) values (623, 'Throw Pillow Covers', 1367.08);
insert into products (id, product_name, price) values (624, 'Beef Chili', 958.92);
insert into products (id, product_name, price) values (625, 'Chipotle Seasoning Blend', 1133.17);
insert into products (id, product_name, price) values (626, 'Cranberry Pecan Granola', 5040.93);
insert into products (id, product_name, price) values (627, 'Apple Cinnamon Granola', 1474.61);
insert into products (id, product_name, price) values (628, 'Salsa Verde', 9089.69);
insert into products (id, product_name, price) values (629, 'DIY Lip Balm Kit', 9253.62);
insert into products (id, product_name, price) values (630, 'Pet Tracking Collar', 5341.77);
insert into products (id, product_name, price) values (631, 'Air Purifier', 5801.93);
insert into products (id, product_name, price) values (632, 'Kids'' Educational Tablet', 1696.41);
insert into products (id, product_name, price) values (633, 'Bock Beer Mustard', 4659.37);
insert into products (id, product_name, price) values (634, 'Almond Flour Pancake Mix', 5763.97);
insert into products (id, product_name, price) values (635, 'Shatterproof Wine Glasses', 3854.64);
insert into products (id, product_name, price) values (636, 'Mechanical Keyboard', 2955.24);
insert into products (id, product_name, price) values (637, 'LED Desk Lamp with USB Charging Port', 4951.04);
insert into products (id, product_name, price) values (638, 'Peach Slices (canned)', 5899.93);
insert into products (id, product_name, price) values (639, 'Peanut Butter Banana Smoothie Mix', 4524.21);
insert into products (id, product_name, price) values (640, 'Manual Coffee Grinder', 3801.41);
insert into products (id, product_name, price) values (641, 'Fitness Tracker Watch', 782.60);
insert into products (id, product_name, price) values (642, 'Magnetic Screen Door', 1319.65);
insert into products (id, product_name, price) values (643, 'Maple Bacon Potato Chips', 3660.09);
insert into products (id, product_name, price) values (644, 'Cat Tree', 6092.55);
insert into products (id, product_name, price) values (645, 'Honey Glazed Carrots', 3445.92);
insert into products (id, product_name, price) values (646, 'Stuffed Peppers with Quinoa', 7501.99);
insert into products (id, product_name, price) values (647, 'Backpacking Tent', 1578.43);
insert into products (id, product_name, price) values (648, 'Almond Milk', 4464.21);
insert into products (id, product_name, price) values (649, 'Screen Cleaning Kit', 5365.94);
insert into products (id, product_name, price) values (650, 'Black Bean & Corn Salad', 5179.61);
insert into products (id, product_name, price) values (651, 'Vegetable Stir-Fry Sauce', 6731.18);
insert into products (id, product_name, price) values (652, 'Compost Bin', 5876.50);
insert into products (id, product_name, price) values (653, 'Glass Water Bottle', 7887.66);
insert into products (id, product_name, price) values (654, 'Chocolate Covered Pretzels', 3803.81);
insert into products (id, product_name, price) values (655, 'Lentil Vegetable Curry', 4358.66);
insert into products (id, product_name, price) values (656, 'Fall-Themed Table Runner', 5041.19);
insert into products (id, product_name, price) values (657, 'Wooden Blocks', 1071.47);
insert into products (id, product_name, price) values (658, 'Pumpkin Spice Creamer', 3765.85);
insert into products (id, product_name, price) values (659, 'Green Tea Matcha Powder', 5104.50);
insert into products (id, product_name, price) values (660, 'Travel Orthopedic Pillow', 6067.47);
insert into products (id, product_name, price) values (661, 'Pasta Salad Kit', 5057.45);
insert into products (id, product_name, price) values (662, 'Smartphone Car Mount with Wireless Charging', 6747.12);
insert into products (id, product_name, price) values (663, 'Lentils', 2369.81);
insert into products (id, product_name, price) values (664, 'Cranberry Almond Biscotti', 4709.86);
insert into products (id, product_name, price) values (665, 'Travel Shoe Bags Set', 6016.24);
insert into products (id, product_name, price) values (666, 'Scented Soy Candles', 384.71);
insert into products (id, product_name, price) values (667, 'Cranberry Orange Juice', 561.02);
insert into products (id, product_name, price) values (668, 'Portable Solar Generator', 1424.51);
insert into products (id, product_name, price) values (669, 'Tattoo Kit', 2741.39);
insert into products (id, product_name, price) values (670, 'Smart Wi-Fi Light Bulbs', 1362.60);
insert into products (id, product_name, price) values (671, 'Pumpkin Seeds', 9343.37);
insert into products (id, product_name, price) values (672, 'Pet Training Clicker', 4062.92);
insert into products (id, product_name, price) values (673, 'Active Racerback Tank', 3609.58);
insert into products (id, product_name, price) values (674, 'LED Desk Lamp with USB Charging Port', 3776.62);
insert into products (id, product_name, price) values (675, 'Barbecue Chicken Pizza', 3504.74);
insert into products (id, product_name, price) values (676, 'Workstation Laptop Stand', 859.78);
insert into products (id, product_name, price) values (677, 'Mango Salsa', 9074.85);
insert into products (id, product_name, price) values (678, 'Tomato Paste', 9462.82);
insert into products (id, product_name, price) values (679, 'Savory Italian Herbs', 7496.45);
insert into products (id, product_name, price) values (680, 'Vegetable Sushi Rolls', 51.08);
insert into products (id, product_name, price) values (681, 'LED Flashlight with Rechargeable Batteries', 6149.02);
insert into products (id, product_name, price) values (682, 'Coconut Curry Lentil Soup', 9216.86);
insert into products (id, product_name, price) values (683, 'Classic Chicken Noodle Soup', 8665.00);
insert into products (id, product_name, price) values (684, 'Cordless Water Flosser', 6859.52);
insert into products (id, product_name, price) values (685, 'Portable Campfire', 4587.68);
insert into products (id, product_name, price) values (686, 'Handheld Shower Head', 4924.06);
insert into products (id, product_name, price) values (687, 'Personal Security Alarm Keychain', 3222.67);
insert into products (id, product_name, price) values (688, 'Tailored Blazer', 9759.98);
insert into products (id, product_name, price) values (689, 'Zucchini Noodle Pasta', 8856.39);
insert into products (id, product_name, price) values (690, 'Wall Art Stickers', 1745.51);
insert into products (id, product_name, price) values (691, 'French Bread', 7709.43);
insert into products (id, product_name, price) values (692, 'Casual Long Cardigan', 4972.07);
insert into products (id, product_name, price) values (693, 'Personal Blender with Travel Lid', 3503.72);
insert into products (id, product_name, price) values (694, 'Almond Flour Tortillas', 4510.53);
insert into products (id, product_name, price) values (695, 'Pet Hair Vacuum Cleaner Attachment', 9931.69);
insert into products (id, product_name, price) values (696, 'Kale Chips', 355.98);
insert into products (id, product_name, price) values (697, 'Smartphone Car Mount with Wireless Charging', 635.30);
insert into products (id, product_name, price) values (698, 'Cranberry Almond Cookies', 4674.25);
insert into products (id, product_name, price) values (699, 'Pineapple Coconut Rice Mix', 3893.92);
insert into products (id, product_name, price) values (700, 'Vegan Mayonnaise', 472.30);
insert into products (id, product_name, price) values (701, 'Chocolate Chip Cliff Bars', 5696.45);
insert into products (id, product_name, price) values (702, 'Savory Mushroom Risotto', 9673.08);
insert into products (id, product_name, price) values (703, 'Thai Peanut Noodles', 8065.70);
insert into products (id, product_name, price) values (704, 'Pesto Pasta Sauce', 7519.05);
insert into products (id, product_name, price) values (705, 'Vegetable Stock', 565.15);
insert into products (id, product_name, price) values (706, 'Whole Grain Cereal', 6206.27);
insert into products (id, product_name, price) values (707, 'Collapsible Pet Dog Bowl', 1870.41);
insert into products (id, product_name, price) values (708, 'Fitness Activity Journal', 9009.57);
insert into products (id, product_name, price) values (709, 'Peanut Butter Banana Smoothie', 6348.45);
insert into products (id, product_name, price) values (710, 'Golf Polo Shirt', 5662.79);
insert into products (id, product_name, price) values (711, 'Vegetarian Sausage Links', 8113.97);
insert into products (id, product_name, price) values (712, 'Weighted Jump Rope with Counter', 3929.40);
insert into products (id, product_name, price) values (713, 'Coconut Bowls Set', 8034.84);
insert into products (id, product_name, price) values (714, 'Sporty Slide Sandals', 7349.65);
insert into products (id, product_name, price) values (715, 'Feta Cheese', 9139.91);
insert into products (id, product_name, price) values (716, 'Nutty Trail Mix', 5601.37);
insert into products (id, product_name, price) values (717, 'Fleece Lined Leggings', 4705.23);
insert into products (id, product_name, price) values (718, 'Wire Shelving Unit', 499.36);
insert into products (id, product_name, price) values (719, 'Legging Pants', 3043.72);
insert into products (id, product_name, price) values (720, 'Electric Kettle with Temperature Control', 3554.76);
insert into products (id, product_name, price) values (721, 'Kale Caesar Salad Kit', 4394.16);
insert into products (id, product_name, price) values (722, 'Pesto Pasta Sauce', 3758.28);
insert into products (id, product_name, price) values (723, 'Spinach and Cheese Stuffed Shells', 1559.71);
insert into products (id, product_name, price) values (724, 'Chipotle Seasoning Blend', 2750.62);
insert into products (id, product_name, price) values (725, 'Body Pillow Case', 5820.58);
insert into products (id, product_name, price) values (726, 'Multi-Layer Food Steamer', 2733.91);
insert into products (id, product_name, price) values (727, 'Peach & Mango Salsa', 2565.61);
insert into products (id, product_name, price) values (728, 'Personal Safety Alarm', 3854.50);
insert into products (id, product_name, price) values (729, 'Dog Frisbee Toy', 5394.10);
insert into products (id, product_name, price) values (730, 'Cranberry Orange Oatmeal', 4164.21);
insert into products (id, product_name, price) values (731, 'LED Camping Lantern with USB Charging', 6239.06);
insert into products (id, product_name, price) values (732, 'Radish Chips', 9611.13);
insert into products (id, product_name, price) values (733, 'Reclining Camping Chair', 9361.31);
insert into products (id, product_name, price) values (734, 'Car Seat Organizer', 3720.71);
insert into products (id, product_name, price) values (735, 'Heavy-Duty Utility Tote', 3182.26);
insert into products (id, product_name, price) values (736, 'Chipotle Sauce', 4185.83);
insert into products (id, product_name, price) values (737, 'Coconut Macaroons', 6590.99);
insert into products (id, product_name, price) values (738, 'Fresh Cilantro', 3555.14);
insert into products (id, product_name, price) values (739, 'Leather Wallet', 3145.45);
insert into products (id, product_name, price) values (740, 'Pumpkin Pancake Mix', 2323.31);
insert into products (id, product_name, price) values (741, 'Glass Water Bottle', 1450.14);
insert into products (id, product_name, price) values (742, 'Vegetarian Stir Fry Sauce', 9946.87);
insert into products (id, product_name, price) values (743, 'Gluten-Free Pancake Mix', 8993.98);
insert into products (id, product_name, price) values (744, 'Plant-Based Protein Bars', 4096.18);
insert into products (id, product_name, price) values (745, 'Window Bird Feeder with Suction Cups', 3472.59);
insert into products (id, product_name, price) values (746, 'Party Mini Dress', 599.28);
insert into products (id, product_name, price) values (747, 'Electric Blanket', 187.96);
insert into products (id, product_name, price) values (748, 'Italian Pasta', 2902.77);
insert into products (id, product_name, price) values (749, 'Sweet Chili Thai Sauce', 7345.44);
insert into products (id, product_name, price) values (750, 'Sourdough Bread', 713.28);
insert into products (id, product_name, price) values (751, 'High-Quality Yoga Mat', 7800.38);
insert into products (id, product_name, price) values (752, 'Silicone Baking Mat', 7195.19);
insert into products (id, product_name, price) values (753, 'Nutritional Yeast', 5715.16);
insert into products (id, product_name, price) values (754, 'Faux Leather Leggings', 9660.19);
insert into products (id, product_name, price) values (755, 'Motorcycle Phone Mount', 4985.93);
insert into products (id, product_name, price) values (756, 'Creamy Spinach Dip', 7821.33);
insert into products (id, product_name, price) values (757, 'Portable Massage Table', 6458.60);
insert into products (id, product_name, price) values (758, 'Air Fryer', 8176.20);
insert into products (id, product_name, price) values (759, 'Luxury Bath Robe', 890.60);
insert into products (id, product_name, price) values (760, 'Self-Stirring Mug', 3931.03);
insert into products (id, product_name, price) values (761, 'Kale & Quinoa Salad Mix', 8753.94);
insert into products (id, product_name, price) values (762, 'Pumpkin Spice Cookies', 6626.49);
insert into products (id, product_name, price) values (763, 'Classic Caesar Dressing', 363.25);
insert into products (id, product_name, price) values (764, 'Thai Peanut Dressing', 3659.17);
insert into products (id, product_name, price) values (765, 'Sketchbook', 5841.16);
insert into products (id, product_name, price) values (766, 'Organic Coconut Sugar', 8710.55);
insert into products (id, product_name, price) values (767, 'Sweet Chili Thai Sauce', 3677.56);
insert into products (id, product_name, price) values (768, 'Blueberry Chia Jam', 9360.99);
insert into products (id, product_name, price) values (769, 'Frozen Hash Browns', 1989.53);
insert into products (id, product_name, price) values (770, 'Trendy Bomber Jacket', 1495.34);
insert into products (id, product_name, price) values (771, 'Non-Stick Crepe Pan', 3613.46);
insert into products (id, product_name, price) values (772, 'Organic Baby Spinach', 6890.36);
insert into products (id, product_name, price) values (773, 'Chicken Sausage', 6527.29);
insert into products (id, product_name, price) values (774, 'Herbal Tea Variety Pack', 2340.53);
insert into products (id, product_name, price) values (775, 'Heated Throw Blanket', 8191.05);
insert into products (id, product_name, price) values (776, 'Summer Tank Dress', 3911.65);
insert into products (id, product_name, price) values (777, 'Biodegradable Dog Waste Bags', 9247.17);
insert into products (id, product_name, price) values (778, 'Phone Case', 9203.39);
insert into products (id, product_name, price) values (779, 'Compost Bin', 6471.69);
insert into products (id, product_name, price) values (780, 'Portable Bluetooth Headphones', 3870.01);
insert into products (id, product_name, price) values (781, 'Portable Grill Cover', 8171.18);
insert into products (id, product_name, price) values (782, 'Kids'' Dinosaur-Themed Lunchbox', 88.06);
insert into products (id, product_name, price) values (783, 'Wrist Support Brace', 124.05);
insert into products (id, product_name, price) values (784, 'Fruit and Nut Bars', 1682.75);
insert into products (id, product_name, price) values (785, 'Wireless Security System', 6223.83);
insert into products (id, product_name, price) values (786, 'Spicy Italian Sausage', 2916.04);
insert into products (id, product_name, price) values (787, 'Compressible Packing Cubes', 2147.81);
insert into products (id, product_name, price) values (788, 'Pet Camera with Treat Dispenser', 9739.59);
insert into products (id, product_name, price) values (789, 'Asian Noodle Salad Kit', 3564.61);
insert into products (id, product_name, price) values (790, 'Bamboo Toothbrush Holder', 1033.14);
insert into products (id, product_name, price) values (791, 'Sous Vide Cooker', 6182.73);
insert into products (id, product_name, price) values (792, 'Silicone Ice Cube Tray', 4138.66);
insert into products (id, product_name, price) values (793, 'Cranberry Pecan Granola', 7510.88);
insert into products (id, product_name, price) values (794, 'USB Flash Drive', 6775.73);
insert into products (id, product_name, price) values (795, 'Bamboo Toothbrush', 5035.08);
insert into products (id, product_name, price) values (796, 'Kids'' Trampoline', 8020.27);
insert into products (id, product_name, price) values (797, 'Ice Cream Maker', 3070.36);
insert into products (id, product_name, price) values (798, 'Air Mattress', 9891.09);
insert into products (id, product_name, price) values (799, 'Luxury Yoga Mat', 1066.08);
insert into products (id, product_name, price) values (800, 'Running Shorts', 4609.03);
insert into products (id, product_name, price) values (801, 'Electric Meat Grinder', 4015.00);
insert into products (id, product_name, price) values (802, 'Margherita Pizza', 5593.42);
insert into products (id, product_name, price) values (803, 'Travel Jewelry Organizer', 2574.36);
insert into products (id, product_name, price) values (804, 'Vegetarian Stir Fry Sauce', 8358.57);
insert into products (id, product_name, price) values (805, 'Coconut Milk Yogurt', 1365.06);
insert into products (id, product_name, price) values (806, 'Greek Feta Cheese', 7842.72);
insert into products (id, product_name, price) values (807, 'Smart WiFi Plug', 1914.88);
insert into products (id, product_name, price) values (808, 'Personal Blender with Cups', 149.81);
insert into products (id, product_name, price) values (809, 'Spicy Tuna Rolls', 9228.58);
insert into products (id, product_name, price) values (810, 'Cereal Dispenser with Portion Control', 143.95);
insert into products (id, product_name, price) values (811, 'Weighted Blanket', 9318.69);
insert into products (id, product_name, price) values (812, 'Quinoa', 9720.70);
insert into products (id, product_name, price) values (813, 'Maple Pecan Granola', 7033.94);
insert into products (id, product_name, price) values (814, 'Dog Frisbee Toy', 9291.20);
insert into products (id, product_name, price) values (815, 'Stainless Steel Travel Mug', 9523.69);
insert into products (id, product_name, price) values (816, 'Digital Wireless Meat Thermometer', 5565.44);
insert into products (id, product_name, price) values (817, 'Folding Pocket Knife', 6259.48);
insert into products (id, product_name, price) values (818, 'Buffalo Chicken Dip', 2645.46);
insert into products (id, product_name, price) values (819, 'Frozen Edamame', 6657.29);
insert into products (id, product_name, price) values (820, 'Multi-Purpose Marine Rope', 5745.41);
insert into products (id, product_name, price) values (821, 'Deluxe First Aid Kit', 7658.62);
insert into products (id, product_name, price) values (822, 'Running Shorts', 6095.58);
insert into products (id, product_name, price) values (823, 'Organic Quinoa Salad', 6947.39);
insert into products (id, product_name, price) values (824, 'Insulated Lunch Bag', 1143.56);
insert into products (id, product_name, price) values (825, 'Outdoor Camping Hammock', 745.48);
insert into products (id, product_name, price) values (826, 'Blender Bottle', 8656.88);
insert into products (id, product_name, price) values (827, 'Tennis Racket', 9896.93);
insert into products (id, product_name, price) values (828, 'Ripped Boyfriend Jeans', 7813.64);
insert into products (id, product_name, price) values (829, 'Turmeric Ginger Tea', 5260.14);
insert into products (id, product_name, price) values (830, 'Wireless Charger Stand', 5430.86);
insert into products (id, product_name, price) values (831, 'Faux Fur Throw Blanket', 3524.64);
insert into products (id, product_name, price) values (832, 'Shower Curtain Hooks', 8598.67);
insert into products (id, product_name, price) values (833, 'Chiffon Blouse', 4704.42);
insert into products (id, product_name, price) values (834, 'Cable Knit Beanie', 7279.10);
insert into products (id, product_name, price) values (835, 'DIY Lip Balm Making Kit', 9225.93);
insert into products (id, product_name, price) values (836, 'Adjustable Pet Grooming Table', 6833.43);
insert into products (id, product_name, price) values (837, 'Adjustable Height Standing Desk Converter', 1016.27);
insert into products (id, product_name, price) values (838, 'Wireless Mouse', 8688.56);
insert into products (id, product_name, price) values (839, 'Set of Gardening Gloves with Claws', 2154.11);
insert into products (id, product_name, price) values (840, 'Slim Fit Chinos', 3292.55);
insert into products (id, product_name, price) values (841, 'Chocolate Almond Milk', 2004.62);
insert into products (id, product_name, price) values (842, 'Garden Kneeler and Seat', 7492.28);
insert into products (id, product_name, price) values (843, 'Butternut Squash Ravioli', 2048.42);
insert into products (id, product_name, price) values (844, 'Black Bean Spaghetti', 211.93);
insert into products (id, product_name, price) values (845, 'Artisan Flatbreads', 8743.87);
insert into products (id, product_name, price) values (846, 'Honey Nut Cheerios', 35.89);
insert into products (id, product_name, price) values (847, 'Pork Tenderloin', 8773.24);
insert into products (id, product_name, price) values (848, 'Foldable Electric Scooter', 5951.69);
insert into products (id, product_name, price) values (849, 'Outdoor Picnic Blanket', 9763.33);
insert into products (id, product_name, price) values (850, 'Organic Whole Wheat Flour', 5092.25);
insert into products (id, product_name, price) values (851, 'Wall-Mounted Wine Rack', 2128.92);
insert into products (id, product_name, price) values (852, 'Reusable Produce Bags Set', 4961.67);
insert into products (id, product_name, price) values (853, 'Portable Pet Pooper Scooper', 1481.18);
insert into products (id, product_name, price) values (854, 'Chili Lime Seasoning', 7633.69);
insert into products (id, product_name, price) values (855, 'Banana Nut Oatmeal Cups', 4134.91);
insert into products (id, product_name, price) values (856, 'Slim Fit Chinos', 9399.09);
insert into products (id, product_name, price) values (857, 'Outdoor Picnic Blanket', 3056.15);
insert into products (id, product_name, price) values (858, 'Zesty Cilantro Lime Dressing', 5277.42);
insert into products (id, product_name, price) values (859, 'Vegan Chocolate Cake Mix', 686.95);
insert into products (id, product_name, price) values (860, 'Pumpkin Spice Cookies', 2044.87);
insert into products (id, product_name, price) values (861, 'Compact Digital Camera', 9114.25);
insert into products (id, product_name, price) values (862, 'Blackberry Jam', 3824.42);
insert into products (id, product_name, price) values (863, 'Chiffon Blouse', 8214.12);
insert into products (id, product_name, price) values (864, 'Chocolate Syrup', 6986.39);
insert into products (id, product_name, price) values (865, 'Insulated Lunch Bag', 2757.20);
insert into products (id, product_name, price) values (866, 'Wall Planner', 1164.86);
insert into products (id, product_name, price) values (867, 'Sweet Potatoes', 8320.84);
insert into products (id, product_name, price) values (868, 'Frozen Edamame', 7087.75);
insert into products (id, product_name, price) values (869, 'Maxi Wrap Dress', 772.17);
insert into products (id, product_name, price) values (870, 'Pasta Primavera', 2162.68);
insert into products (id, product_name, price) values (871, 'Sriracha Chili Sauce', 684.58);
insert into products (id, product_name, price) values (872, 'Creamy Tomato Basil Soup', 3971.63);
insert into products (id, product_name, price) values (873, 'Portable Charcoal Grill', 4954.15);
insert into products (id, product_name, price) values (874, 'Basketball', 8401.25);
insert into products (id, product_name, price) values (875, 'Pumpkin Puree', 6894.25);
insert into products (id, product_name, price) values (876, 'Apple Cinnamon Breakfast Muffins', 951.30);
insert into products (id, product_name, price) values (877, 'Black Bean Soup', 579.64);
insert into products (id, product_name, price) values (878, 'Frozen Broccoli', 5858.32);
insert into products (id, product_name, price) values (879, 'Weighted Blanket', 896.09);
insert into products (id, product_name, price) values (880, 'Digital Wireless Camera', 1342.69);
insert into products (id, product_name, price) values (881, 'Pear and Gorgonzola Salad', 9248.19);
insert into products (id, product_name, price) values (882, 'Tropical Fruit Bowl', 9468.28);
insert into products (id, product_name, price) values (883, 'Mediterranean Couscous', 5632.35);
insert into products (id, product_name, price) values (884, 'Rolling Cooler', 139.02);
insert into products (id, product_name, price) values (885, 'Active Racerback Tank', 3804.85);
insert into products (id, product_name, price) values (886, 'Honey Mustard Sauce', 7028.70);
insert into products (id, product_name, price) values (887, 'Garlic Naan Bread', 3567.81);
insert into products (id, product_name, price) values (888, 'Sweet Cherry Tomatoes', 8683.10);
insert into products (id, product_name, price) values (889, 'LED Desk Lamp with USB Charging Port', 9329.27);
insert into products (id, product_name, price) values (890, 'Smart Water Bottle with Hydration Reminder', 1774.44);
insert into products (id, product_name, price) values (891, 'Homestyle Beef Stew', 6950.25);
insert into products (id, product_name, price) values (892, 'Portable Laptop Table', 2325.64);
insert into products (id, product_name, price) values (893, 'Chocolate Coconut Protein Balls', 6589.69);
insert into products (id, product_name, price) values (894, 'Stainless Steel Water Bottle', 2842.99);
insert into products (id, product_name, price) values (895, 'Chocolate Coconut Protein Balls', 5813.49);
insert into products (id, product_name, price) values (896, 'Coconut Water', 3255.88);
insert into products (id, product_name, price) values (897, 'Pet Bed', 7358.72);
insert into products (id, product_name, price) values (898, 'Handcrafted Wooden Jewelry Box', 8516.20);
insert into products (id, product_name, price) values (899, 'Board Game Storage', 1999.51);
insert into products (id, product_name, price) values (900, 'Buffalo Sauce', 6161.10);
insert into products (id, product_name, price) values (901, 'Asian Noodle Salad Kit', 4436.77);
insert into products (id, product_name, price) values (902, 'Spicy Chicken Wings', 4772.77);
insert into products (id, product_name, price) values (903, 'Canvas Tote Bag', 446.27);
insert into products (id, product_name, price) values (904, 'Pet Camera with Treat Dispenser', 213.73);
insert into products (id, product_name, price) values (905, 'Organic Baby Spinach', 3466.36);
insert into products (id, product_name, price) values (906, 'Phone Screen Protector', 1266.51);
insert into products (id, product_name, price) values (907, 'Peach Slices in Syrup', 1856.13);
insert into products (id, product_name, price) values (908, 'Watercolor Paint Set', 7615.29);
insert into products (id, product_name, price) values (909, 'Natural Soy Candles', 6080.37);
insert into products (id, product_name, price) values (910, 'Silicone Ice Cube Tray', 2887.63);
insert into products (id, product_name, price) values (911, 'Wireless Gaming Headset', 2745.26);
insert into products (id, product_name, price) values (912, 'Balsamic Salad Dressing', 3774.30);
insert into products (id, product_name, price) values (913, 'Mediterranean Chickpea Salad', 8424.70);
insert into products (id, product_name, price) values (914, 'Warm Knit Beanie', 1807.92);
insert into products (id, product_name, price) values (915, 'Kale Salad with Lemon Dressing', 7562.55);
insert into products (id, product_name, price) values (916, 'Pet Travel Bed', 3450.81);
insert into products (id, product_name, price) values (917, 'Puffed Rice Cake', 8182.36);
insert into products (id, product_name, price) values (918, 'Honey Butter Popcorn', 5135.31);
insert into products (id, product_name, price) values (919, 'Self-Cleaning Water Bottle', 4712.19);
insert into products (id, product_name, price) values (920, 'Instant Camera', 4124.57);
insert into products (id, product_name, price) values (921, 'Pineapple Chunks (canned)', 6282.28);
insert into products (id, product_name, price) values (922, 'Leather Notebook Cover', 8946.28);
insert into products (id, product_name, price) values (923, 'Gardening Tool Belt', 5039.35);
insert into products (id, product_name, price) values (924, 'Essential Oil Roller Bottles', 4219.43);
insert into products (id, product_name, price) values (925, 'Waffle Maker', 8376.30);
insert into products (id, product_name, price) values (926, 'Chicken Sausage', 4205.08);
insert into products (id, product_name, price) values (927, 'Black Bean Soup', 5303.31);
insert into products (id, product_name, price) values (928, 'Premium Flashlight', 6635.47);
insert into products (id, product_name, price) values (929, 'Cork Yoga Mat', 6018.84);
insert into products (id, product_name, price) values (930, 'Savory Oats', 5664.83);
insert into products (id, product_name, price) values (931, 'Personal Blender with Travel Cup', 8339.62);
insert into products (id, product_name, price) values (932, 'Surimi Crab Sticks', 4562.03);
insert into products (id, product_name, price) values (933, 'Acoustic Guitar', 8101.12);
insert into products (id, product_name, price) values (934, 'Classic Pesto Sauce', 838.78);
insert into products (id, product_name, price) values (935, 'Sketchbook', 2448.32);
insert into products (id, product_name, price) values (936, 'Garlic Butter Sauce', 4905.36);
insert into products (id, product_name, price) values (937, 'Handheld Vacuum', 219.15);
insert into products (id, product_name, price) values (938, 'Portable SSD', 2263.79);
insert into products (id, product_name, price) values (939, 'Customizable Photo Calendar', 1240.96);
insert into products (id, product_name, price) values (940, 'Sweet and Spicy Barbecue Sauce', 90.82);
insert into products (id, product_name, price) values (941, 'Digital Kitchen Timer', 8074.26);
insert into products (id, product_name, price) values (942, 'Wireless Keyboard and Mouse Combo', 5850.78);
insert into products (id, product_name, price) values (943, 'Smartphone Car Mount with Wireless Charging', 5771.05);
insert into products (id, product_name, price) values (944, 'Silicone Baking Cups', 9631.37);
insert into products (id, product_name, price) values (945, 'Sesame Ginger Dressing', 9699.39);
insert into products (id, product_name, price) values (946, 'Almond Milk Yogurt', 802.47);
insert into products (id, product_name, price) values (947, 'Herb Seasoned Rice', 9797.57);
insert into products (id, product_name, price) values (948, 'Strawberry Fruit Spread', 2486.15);
insert into products (id, product_name, price) values (949, 'Organic Black Beans', 1369.40);
insert into products (id, product_name, price) values (950, 'Over-the-Door Hooks', 8320.28);
insert into products (id, product_name, price) values (951, 'Instant Mashed Potatoes', 3914.84);
insert into products (id, product_name, price) values (952, 'Garlic Parmesan Roasted Potatoes', 4525.43);
insert into products (id, product_name, price) values (953, 'Puzzle Mat', 76.76);
insert into products (id, product_name, price) values (954, 'Sweet Potatoes', 7791.21);
insert into products (id, product_name, price) values (955, 'Cinnamon Spiced Almonds', 9976.44);
insert into products (id, product_name, price) values (956, 'Crafting Kit', 3836.42);
insert into products (id, product_name, price) values (957, 'Cauliflower Gnocchi', 4037.84);
insert into products (id, product_name, price) values (958, 'Peanut Butter', 4431.09);
insert into products (id, product_name, price) values (959, 'Pumpkin Pancake Mix', 4645.62);
insert into products (id, product_name, price) values (960, 'Decorative Throw Pillows', 5468.25);
insert into products (id, product_name, price) values (961, 'Stainless Steel Cutlery Set', 6381.75);
insert into products (id, product_name, price) values (962, 'Faux Leather Leggings', 3976.09);
insert into products (id, product_name, price) values (963, 'Casual Cropped Sweater', 4650.47);
insert into products (id, product_name, price) values (964, 'Wireless Charging Station', 1416.89);
insert into products (id, product_name, price) values (965, 'Roasted Vegetable Medley', 1591.21);
insert into products (id, product_name, price) values (966, 'Classic Black Dress', 7825.31);
insert into products (id, product_name, price) values (967, 'Pet Tracking Collar', 2482.89);
insert into products (id, product_name, price) values (968, 'Kitchen Scale', 9592.99);
insert into products (id, product_name, price) values (969, 'Fleece Throw Blanket', 6718.85);
insert into products (id, product_name, price) values (970, 'Silicone Cooking Utensils Set', 8775.91);
insert into products (id, product_name, price) values (971, 'Pineapple Coconut Bars', 5596.76);
insert into products (id, product_name, price) values (972, 'High-Top Leather Boots', 8751.12);
insert into products (id, product_name, price) values (973, 'Juice Extractor', 2061.61);
insert into products (id, product_name, price) values (974, 'Fitbit Activity Tracker', 9517.19);
insert into products (id, product_name, price) values (975, 'Honey Garlic Chicken', 9273.71);
insert into products (id, product_name, price) values (976, 'Golf Polo Shirt', 134.99);
insert into products (id, product_name, price) values (977, 'Chickpea Salad Deluxe', 9623.31);
insert into products (id, product_name, price) values (978, 'Olive Oil', 7357.60);
insert into products (id, product_name, price) values (979, 'Hand Crank Blender', 6904.44);
insert into products (id, product_name, price) values (980, 'Relaxed Fit Henley Shirt', 766.89);
insert into products (id, product_name, price) values (981, 'Bluetooth Tracker', 1852.85);
insert into products (id, product_name, price) values (982, 'Gaming Mousepad', 9952.51);
insert into products (id, product_name, price) values (983, 'Black Olives', 2790.40);
insert into products (id, product_name, price) values (984, 'Stylish Combat Boots', 5048.55);
insert into products (id, product_name, price) values (985, 'Crew Neck Sweater', 1394.10);
insert into products (id, product_name, price) values (986, 'Pear and Gorgonzola Salad', 4939.16);
insert into products (id, product_name, price) values (987, 'Scent Diffuser', 98.47);
insert into products (id, product_name, price) values (988, 'Fettuccine Alfredo Dinner Kit', 4962.17);
insert into products (id, product_name, price) values (989, 'Chili Garlic Sauce', 8553.94);
insert into products (id, product_name, price) values (990, 'Adjustable Dog Harness', 39.91);
insert into products (id, product_name, price) values (991, 'Frozen Salmon Filets', 7569.74);
insert into products (id, product_name, price) values (992, 'Organic Coconut Oil', 6892.77);
insert into products (id, product_name, price) values (993, 'Coconut Macaroons', 1553.30);
insert into products (id, product_name, price) values (994, 'Solar String Lights', 5443.79);
insert into products (id, product_name, price) values (995, 'Dill Pickle Chips', 6316.30);
insert into products (id, product_name, price) values (996, 'Digital Voice Recorder', 3324.00);
insert into products (id, product_name, price) values (997, 'Vegetable Broth', 284.08);
insert into products (id, product_name, price) values (998, 'Classic White T-Shirt', 2871.77);
insert into products (id, product_name, price) values (999, 'Creamy Spinach Dip', 3598.30);
insert into products (id, product_name, price) values (1000, 'Antique Style Clock', 7159.83);
